version: '2'
volumes:
  docker-registry-data:
  docker-registry-creds:

services:
  qubeship_app:
    env_file: .env
    environment:
      DEFAULT_LISTENER_PORT: ${APP_PORT}
      CONF_SERVER_TOKEN: ${CONF_SERVER_TOKEN}
      VAULT_TOKEN: ${VAULT_TOKEN}
      ENV_ID: ${ENV_ID}
      CONF_SERVER_ADDR: ${CONF_SERVER_ADDR}
      VAULT_ADDR: ${VAULT_ADDR}
      TENANT: ${TENANT}
      ENV_TYPE: ${ENV_TYPE}
      URL_BASE: ${API_URL_BASE}
    image: ${APP_IMAGE}:${APP_VERSION}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - qube-vault-opener

  docker-registry:
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - docker-registry-data:/var/lib/registry
      - docker-registry-creds:/certs
      - docker-registry-creds:/auth
     # - ./qubeship_home/docker-registry/config.yml:/etc/docker/registry/config.yml
    depends_on:
      - registry_copy

  registry_copy:
    env_file: .env
    image: ${QUBE_OPENSSL_IMAGE}:${QUBE_OPENSSL_VERSION}
    #image: busybox
    container_name: registry_copy
    volumes:
      - docker-registry-creds:/certs:rw
      - docker-registry-creds:/auth:rw

  oauth_registrator:
    env_file: .env
    environment:
      APP_CB_URL: http://${QUBE_HOST}:${APP_PORT}/api/v1/auth/callback?provider=github
      CLI_CB_URL: http://cli.qubeship.io/index.html
      BUILDER_CB_URL: http://${QUBE_HOST}:${QUBE_BUILDER_PORT}/securityRealm/finishLogin
    image: "${REGISTRATOR_IMAGE}:${REGISTRATOR_VERSION}"